---
- name: Install and start the nginx server
  hosts: all
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
  - name: start nginx
    services:
      state: present
      enabled: true
